name: appservico
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.7.7
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  geolocator_web: ^3.0.0
  image_picker: ^1.0.0
  path: ^1.8.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_typeahead: ^5.2.0
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
