// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ3A1KiNpKmmcp6NpMtEA7-LIDk8AmsHw',
    appId: '1:886100364182:web:c6d0be80bbd942f4eeebb7',
    messagingSenderId: '886100364182',
    projectId: 'servicojaapp-fc85b',
    authDomain: 'servicojaapp-fc85b.firebaseapp.com',
    storageBucket: 'servicojaapp-fc85b.firebasestorage.app',
    measurementId: 'G-EQ643JGXJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb8Ql4yHqOKO0k_PmK46T4lMG6n2MR18w',
    appId: '1:886100364182:android:c0c9e2df0c5ae36feeebb7',
    messagingSenderId: '886100364182',
    projectId: 'servicojaapp-fc85b',
    storageBucket: 'servicojaapp-fc85b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDirOnSicT29AkDbUba_bXE5UaQq0HYOYk',
    appId: '1:886100364182:ios:a0ab4a547789ffc3eeebb7',
    messagingSenderId: '886100364182',
    projectId: 'servicojaapp-fc85b',
    storageBucket: 'servicojaapp-fc85b.firebasestorage.app',
    iosBundleId: 'com.example.appservico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDirOnSicT29AkDbUba_bXE5UaQq0HYOYk',
    appId: '1:886100364182:ios:a0ab4a547789ffc3eeebb7',
    messagingSenderId: '886100364182',
    projectId: 'servicojaapp-fc85b',
    storageBucket: 'servicojaapp-fc85b.firebasestorage.app',
    iosBundleId: 'com.example.appservico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ3A1KiNpKmmcp6NpMtEA7-LIDk8AmsHw',
    appId: '1:886100364182:web:7df7a723eba5983feeebb7',
    messagingSenderId: '886100364182',
    projectId: 'servicojaapp-fc85b',
    authDomain: 'servicojaapp-fc85b.firebaseapp.com',
    storageBucket: 'servicojaapp-fc85b.firebasestorage.app',
    measurementId: 'G-JMR3LH3541',
  );
}
